version: "3.3"

networks:
  laravel:

services:
  laravel-nginx:
    image: nginx:stable-alpine
    container_name: laravel-nginx
    ports:
      - "8099:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-php
      - laravel-mysql
    networks:
      - laravel
  laravel-mysql:
    image: mysql:5.7.22
    container_name: laravel-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4308:3306"
    volumes:
      - laraveldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel-container-mysql
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  laravel-php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: laravel-php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9022:9000"
    networks:
      - laravel
volumes:
  laraveldata:
    driver: "local"
